### ISSUE TITLE
Editing graphics/ammo quantities and ranges

### ISSUE THREAD

**Issue by kr4g3n** [debugcom/Hacking-F117A#1]
Hi, I just rediscovered this game after watching the new top gun movie and then I found this post today.

First of all can I ask what difficulty settings you were using?

For me it seemed that switching to easy landings opened up the air drop missions,  and then upping to realistic landings opened the airstrip missions. 

Anyway, I plan to read your notes more in depth later, but I donhave a couple of questions/ ideas...

1) you mentioned sprite files; do you think it would be possible to upgrade the graphics by editing these files?

2) do you think it would be possible to edit weapons load outs (maverick and armaam in particular) to increase a) number of munitions loaded per bay, and b) effective range of said munitions?

**Comment by debugcom** [comment]
Hi, thanks for reading.

I generally use Regular or Veteren opponents, Realistic landings, and Microprose F117A (for the extra bays 😜). As I was writing the article, I wondered whether settings had anything to do with availability of missions. Not really sure.

The sprite files I was referring to are basically the world maps for the front end, rather than for the simulation, so there’s 1 sprite file per theater. In theory if someone were to reverse the 3D model format, maybe we could have better looking models, but we’re still limited by flat shading. Not sure if the game has any memory to spare either.

Yes I think you can change the quantity of weapons in each bay. This was the first thing I tried when I was learning how to use Cheat Engine for this article 😜. In order to change the range of weapons, we would have to figure out how the properties are stored. Are they in a table somewhere?

**Comment by kr4g3n** [comment]
Hey thanks for quick response.  I have no Idea as far as tables are concerned I will have a play with cheat engine when I get a chance.

I did just discover this reddit thread - don't know if project is still active or not though https://www.reddit.com/r/hoggit/comments/k4035d/a_remake_of_f19_gunship_2000/&ved=2ahUKEwiEnfjKjp34AhXxAzQIHewCCcUQjjh6BAgJEAE&usg=AOvVaw2HeCSzjp9x5mcopBPNCOwQ
